### PR TITLE
Melt temp config and refactoring of original additions

### PR DESCRIPTION
**Pull request by Traister101**
### New
Melting temperature configuration for all added metals.
Added Metallum Lang file (for the config)
Renamed textures and json assets for tough alloy from "Tough" to "Tough Alloy" (registry name has not changed)
Toggle for Vein json management so custom vein data for modpacks is easily accomplished 

### No more log spam
Vein json errors fixed as well as recipe errors 
All default recipes have a new condition property allowing us to disable them
For aluminium the condition property looks like this 

`"conditions": [
	{
		"type": "tfcmetallum:config",
		"config": "aluminium",
		"value": "true"
	}
  	],`
### Other
And a few commits to clean up some mess I did earlier
Reworked the registration checks so they are more readable (and not as many if's)

### CODE REVIEW

**Comment by Traister101** [comment]
@DisasterMoo I feel happy and satisfied with that I've done here. Even solved the log spam issue when things are disabled (whoops) I'll ping ya on discord later tomorrow if you don't seem to have seen this. Anyway it's 4am and now I'm off to bed gonna sleep like a baby now that this isn't weighing down my conscience

**Comment by DisasterMoo** [comment]
Seems you made a few more commits, is it fine to merge?

**Comment by Traister101** [comment]
Yep, thought I'd say so over discord but it's been a few hours so I'll so so here as well

**Comment by DisasterMoo** [comment]
Got it!

**Pull request merged**
